{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{ldelim} "datatypestring":"{$attribute.data_type_string|wash('javascript')}", "content":[
{foreach $attribute.content.author_list as $author}
{ldelim}"name":"{$author.name|wash('javascript')}", "email":"{$author.email|wash('javascript')}", "id":{$author.id}{ldelim}
{/foreach}
]
{rdelim}