{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<{$attribute.contentclass_attribute_identifier}{if is_unset( $nonamespace )} datatypestring="{$attribute.data_type_string|washxml}"{/if}>
{foreach $attribute.content.author_list as $author}
<author><name>{$author.item.name|washxml}</name><email>{$author.item.email|washxml}</email><id>{$author.item.id}</id></author>
{/foreach}
</{$attribute.contentclass_attribute_identifier}>