{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* @todo conform datime format to XSD one, eg: 1999-05-31T13:20:00.000-05:00 *}
<{$attribute.contentclass_attribute_identifier} datatypestring="{$attribute.data_type_string|washxml}">{if $attribute.content.is_valid}{$attribute.content.timestamp|l10n(shortdatetime)}{/if}</{$attribute.contentclass_attribute_identifier}>