{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<{$attribute.contentclass_attribute_identifier} datatypestring="{$attribute.data_type_string|washxml}">
{$attribute.data_text|wash( email )}
</{$attribute.contentclass_attribute_identifier}>