{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<{$attribute.contentclass_attribute_identifier} datatypestring="{$attribute.data_type_string|washxml}">
{let matrix=$attribute.content}
<table>
<tr>
{section var=ColumnNames loop=$matrix.columns.sequential}
<th>{$ColumnNames.item.name}</th>
{/section}
</tr>
{section var=Rows loop=$matrix.rows.sequential}
<tr>
    {section var=Columns loop=$Rows.item.columns}
    <td>{$Columns.item|washxml}</td>
    {/section}
</tr>
{/section}
</table>
{/let}
</{$attribute.contentclass_attribute_identifier}>