{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* to avoid loops (we do a full tree traversal), we only print out links to related objects *}
{* nb: original template checked if object was in bin to hide it. We don't *}
<{$attribute.contentclass_attribute_identifier}{if is_unset( $nonamespace )} datatypestring="{$attribute.data_type_string|washxml}"{/if}>
{foreach $attribute.content.relation_list as $relation}
<object id="{$relation.contentobject_id}"
        node_id="{$relation.node_id}">
    {* $relation.name *}
</object>
{/foreach}
</{$attribute.contentclass_attribute_identifier}>