{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<{$attribute.contentclass_attribute_identifier} datatypestring="{$attribute.data_type_string|washxml}">
{if $attribute.has_content}
{$attribute.content.name|washxml}
{else}
{'None'|i18n( 'design/standard/content/datatype' )}
{/if}
</{$attribute.contentclass_attribute_identifier}>