{* DO NOT EDIT THIS FILE! Use an override template instead. *}
<{$attribute.contentclass_attribute_identifier} datatypestring="{$attribute.data_type_string|washxml}">
{section show=$attribute.data_text}
<a href="{$attribute.content}">{$attribute.data_text|washxml}</a>
{section-else}
<a href="{$attribute.content}">{$attribute.content|washxml}</a>
{/section}
</{$attribute.contentclass_attribute_identifier}>