{*
 * @version $Id: $
 * @author Gaetano Giunta
 * @copyright (c) 2008-2010 G. Giunta
 * @license code licensed under the GPL License: see README
 *
 * DO NOT EDIT THIS FILE! Use an override template instead.
 *}
{def $attribute=''}
{ldelim}

    "id":{$object.id},
    "name":"{$object.name|wash('javascript')}",
    "class_name":"{$object.class_name|wash('javascript')}",
    "current_version":{$object.current_version},
    "data_map":{ldelim}
{foreach $object.data_map as $name => $item}

      "{$name}":{attribute_view_gui view = json attribute = $item}{delimiter},{/delimiter}
{/foreach}

    {rdelim}

  {rdelim}

{undef $attribute}