{*
 * @version $Id: $
 * @author Gaetano Giunta
 * @copyright (c) 2008-2010 G. Giunta
 * @license code licensed under the GPL License: see README
 *
 * DO NOT EDIT THIS FILE! Use an override template instead.
 *}
  <object id="{$object.id}" name="{$object.name|washxml}" current_version="{$object.current_version}">
    <{$object.class_identifier|washxml}>
{foreach $object.data_map as $item}
{attribute_view_gui view = xml attribute = $item}
{/foreach}

    </{$object.class_identifier|washxml}>
  </object>
