{* DO NOT EDIT THIS FILE! Use an override template instead. *}
{* 'catch-all': if we have no template for a new datatype, we just list its name in the object definition *}
<{$attribute.contentclass_attribute_identifier} />