{*
 * @version $Id: xmlmap.tpl 29 2010-03-19 23:52:02Z gg $
 * @author Gaetano Giunta
 * @copyright (c) 2008-2010 G. Giunta
 * @license code licensed under the GPL License: see README
 *
 * DO NOT EDIT THIS FILE! Use an override template instead.
 *}
<node{if not(is_set($nonamespace))}

  xmlns="{'/xml'|ezurl('no', 'full')}"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="{'/xml/xsd'|ezurl('no', 'full')}"{/if}
  node_id="{$node.node_id}"
  parent_node_id="{$node.parent_node_id}"
  main_node_id="{$node.main_node_id}"
  depth="{$node.depth}">
{content_view_gui view = 'xml' content_object = $node.object}
  <children>
{* @todo verify if using $node.children has same sort order, creates same compiled code *}
{let children = fetch( 'content', 'list', hash( parent_node_id, $node.node_id, sort_by, $node.sort_array ) )}
{foreach $children as $item}
{* NB: full recursive view of all child nodes *}
{node_view_gui view = 'xmlmap' content_node = $item nonamespace = true}
{/foreach}
  </children>
</node>
